spring:
  mail:
    host: smtp.163.com
    username: ********@163.com
    password: **************
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
