spring:
  redis:
    database: 2        # Redis数据库索引（默认为0）
    host: litblue.cn   # Redis服务器地址
    port: 6379         # Redis服务器连接端口
    timeout: 6000      # 链接超时时间 单位 ms（毫秒）

    ################ Redis 线程池设置 ##############
    lettuce:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 1    # 连接池中的最小空闲连接 默认 0
        max-idle: 8    # 连接池中的最大空闲连接 默认 8


